### ISSUE TITLE
Failure messages should be more informative.

### ISSUE THREAD

**Issue by jyasskin** [i-like-robots/chai-html#2]
Right now, a failure produces an error like:

>  expected [ Array(1) ] to deeply equal [ Array(1) ]

It'd be nice to see either the string form of the html on both sides, or a pointer to the location in the tree that didn't match with its contents.

**Comment by i-like-robots** [comment]
I've had a look into this.

Adjusting the message to output the original (or interpreted) HTML is no problem but making this useful for any length of data is tricky.

The difference itself (if supported) will be displayed by the test runner. I could provide the interpreted HTML to this but -- at least with Mocha -- is fairly useless for large strings.

I have a few ideas so will plug away at it.

**Comment by i-like-robots** [comment]
@jyasskin I just published a new prerelease version (0.0.4-0) that has some support for this. Please give it a go and I look forward to your feedback!

**Comment by jyasskin** [comment]
Sorry for taking so long to get back to this. The string output is fine, but unfortunately, it's exposing the issue that Firefox and Chrome serialize attributes in different orders, so there's no input that'll make my test pass. I'll need bbe2b544105fa0dd1512444a1663499f8ac8b785 too.

**Comment by i-like-robots** [comment]
CC #10
