### ISSUE TITLE
Question: Are the failure messages reversed?

### ISSUE THREAD

**Issue by kasperpedersen** [i-like-robots/chai-html#21]
Currently, asserting that `<img>` (actual value) equals `<br>` (expected value) fails with `'tag <img> was changed to tag <br>'`

Generally it looks like the code creates the diff based on the actual value instead of the expected value. Or have I misunderstood something?

**Comment by i-like-robots** [comment]
Looking at the specs I think you might be right... https://github.com/i-like-robots/chai-html/blob/master/tests/spec/chai-html.js#L94-L180
