### ISSUE TITLE
Ignore HTML comments

### ISSUE THREAD

**Issue by danielelkington** [i-like-robots/chai-html#23]
Great plugin! Can an option be added to ignore HTML comments? Something like
`expect('<div><!--Comment--></div>').html.to.ignoringcomments.equal('<div></div>')`

**Comment by i-like-robots** [comment]
That sounds useful and probably not too tricky to add. Would you be willing to have a go at implementing this?

**Comment by danielelkington** [comment]
@i-like-robots Sure, will give it a go.
