### ISSUE TITLE
TypeError: Cannot read property '__location' of undefined

### ISSUE THREAD

**Issue by vmadman** [i-like-robots/chai-html#4]
I'm getting this strange error; I plan to dig in further to understand it a bit better, but my attempts at a quick surface understanding of what's going have so far been fruitless.

I want to leave plenty of room for me just being dumb and overlooking something obvious, but I thought I should post this anyway because my minimum recommendation would be the addition of a more intuitive error.  Anyway, here goes:

**Stacktrace**
```
     TypeError: Cannot read property '__location' of undefined
      at /home/vagrant/node_modules/chai-html/lib/chai-html.js:32:42
      at Array.map (native)
      at extract (/home/vagrant/node_modules/chai-html/lib/chai-html.js:31:15)
      at Assertion.<anonymous> (/home/vagrant/node_modules/chai-html/lib/chai-html.js:60:21)
      at Assertion.ctx.(anonymous function) [as equal] (/home/vagrant/node_modules/chai/lib/chai/utils/overwriteMethod.js:48:33)
      at Object.u.checkHtmlOutput (test/lib/util.js:208:29)
      at Context.<anonymous> (test/layouts.js:24:9)
```

**Usage Code**
```javascript
expect( contents ).html.to.equal( comparisonHtml );
```

**contents**
```html
<body>
     <div class="basic-layout">hello <span>world</span>

</div>
</body>
```

**comparisonHtml**
```html
<body><div class='basic-layout'>hello <span>world</span></div></body>
```

This happens to me every now and then when the HTML for either my `content` or `comparison` are malformed, but otherwise I've got about 50 `chai-html` tests that are working properly.  Usually I just correct the malignant html and it goes away.. but this time the solution is less obvious to me.

I will update this thread with any additional findings.

Also, thanks for the great module :)

**Comment by vmadman** [comment]
I've not yet taken the time to really dive into how `chai-html` actually works, which leaves me a little handicapped in trying to reason through it.  However, testing from the outside it does seem that the error is caused by a **difference** in the two html strings because both of the following assertions pass:

```javascript
expect( contents ).html.to.equal( contents );
expect( comparisonHtml ).html.to.equal( comparisonHtml );
```

Obviously we'd expect them to both pass, but it at least tells me that it's not a parse error of some sort.  Neither of the two strings expose a fundamental flaw in the parser/engine.

**Comment by vmadman** [comment]
I've figured out one way to make the error go away.  As I suspected, the error is seemingly caused by the whitespace differences in the two html strings.  So, I just started to tweak my `comparisonHtml` until the error went away.

**comparisonHtml**
```html
<body> <div class='basic-layout'>hello <span>world</span></div></body>
```

The above represents a string that _passed_ with only one change.  I added a single space between `<body>` and `<div>`.  Since this workaround seems to work, this will probably be my last comment on this issue, at least for now.

Thanks,

**Comment by i-like-robots** [comment]
Thanks for taking the time to look into this. I've made a few changes since the 0.0.4-0 prerelease (see https://github.com/i-like-robots/chai-html/pull/3). I've just published these changes as 0.0.4-1 to try.

Whitespace normalisation is pretty dumb; all newlines are removed and each set of multiple whitespaces are reduced to a single one. I think it would be better to introduce an HTML minifier at this step with a smarter algorithm.

**Comment by vmadman** [comment]
Ah, it makes sense now.  I suspected from the start that it was the whitespace, but I couldn't be sure because the error was _really_ obscure and in other tests `chai-html` was letting me get away with much larger whitespace disparities.  

Then I opened the code and noticed mention of a "walker" and panic flushed over my face, although I've worked with parsers and lexers before, I really wasn't in the mood to go down one of _those_ rabbit holes.. so I was just trying to keep my distance and poke and prod at it.

Now that you've told me about its simple white space approach, it all seems more clear :)

Now that I understand it I think I can easily manage working around it and probably won't ever be bothered again.  For the modules sake, though, its probably a gotcha that most people will hit early on and, as you say, its probably worth looking into a minifer.  I'd even bet that there's more-than-one HTML diff/comparison module on NPM right now... could just solve the whole thing that way.

If that turns into a long, drawn out, thing, though, you could probably just hack a fix in there.  I wonder what would happen if, after your `"   " -> " "`, you trimmed all whitespace before `<` and after `>`.  idk, just thinking out loud..

I'll also definitely check out your latest updates in my next session.

**Comment by vmadman** [comment]
Yeah, this guy looks pretty mature: https://github.com/bem/html-differ -- you should give it a look.

**Comment by i-like-robots** [comment]
Yes, it's one of the first projects I looked at when I was first trying to implement HTML assertions. I can't remember the reasons now for discounting it originally.

It's technique for normalising whitespace is very nearly the same though and it also sorts attributes (a requirement given the parser both projects use).

**Comment by vmadman** [comment]
I don't necessarily think that there is anything wrong with how you handle whitespace.  I mean, whitespace actually does cause HTML to render differently (in some cases and to some extent) and, in fact, I think that converting whitespace to a single `\s` is not very far off from what browsers do, themselves.  So, technically, when I asked `chai-html` to assert those two HTML strings as being equal, and it failed, it behaved appropriately.

I guess the only real problem I had was simply not understanding what the error meant.  It would be super nice if `chai-html` would respond with a diff (somehow) to show me what caused the failure, but perhaps that's not actually necessary.  If it would have just failed with "The two HTML strings do not match", it might have left me less confused.

I'm going to try your latest updates here in a few hours, perhaps its already fixed to the degree that it needs to be.  I just don't want to come across as someone who is insisting that you do anything; I value what you've done already and would be happy to keep on using it as-is.

**Comment by vmadman** [comment]
Oh yes, miles better.  Thank you for this :)
